### PR TITLE
solving circular references

### PR DESCRIPTION
**Pull request by adrielcodeco**

### CODE REVIEW

**Comment by adrielcodeco** [comment]
The test failed in 'npm install' 
Error: No compatible version found: eslint-config-google@'^0.9.1'

**Comment by adrielcodeco** [comment]
develop branch throwing the same error from master only in Node 0.8
Error: No compatible version found: eslint-config-google@'^0.9.1'

**Comment by adrielcodeco** [comment]
@DABH 
what can we do to solve it?

**Comment by DABH** [comment]
Should have based off `develop` not `master` : ) re-opened as #236 !

**Comment by adrielcodeco** [comment]
ok i'll do this but the files changed from master to develop will be the same =(

**Comment by DABH** [comment]
Don’t worry about this I already took care of it in #236 .  Thanks!

**Comment by adrielcodeco** [comment]
ok i'll do this, but the files changed from master to develop will be the same =(

**Pull request closed without merging**
