### PR TITLE
Added ts types to bright colors

### PR DESCRIPTION
**Pull request by nirsky**
Related issue: https://github.com/Marak/colors.js/issues/270

### CODE REVIEW

**Comment by oasis9** [comment]
Can this please be merged? It's been a while and I also intend to use this

**Comment by sportshead** [comment]
@Marak

**Comment by int3nse-git** [comment]
Please merge this

**Comment by nirsky** [comment]
Looks like the repo is abandoned, with no commits since December 2019.
@Marak please consider adding a maintainer.

**Pull request closed without merging**
